Token = 'bot_token'
CommandPrefix = '!'
Description = 'Bot'
Owner_Id = 'id'
Allow_Id = ['id','id']
'''channels'''
channel_bienvenue = 'id'
channel_inscription = 'id'
test_bot = 'id'
message_alliance = 'id'
message_alliance_ig = 'id'
